### ISSUE TITLE
Minified build crashes with java.lang.ClassCastException java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

### ISSUE THREAD

**Issue by mateot1** [Affirm/affirm-merchant-sdk-android#125]
```
Fatal Exception: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
       at com.affirm.android.AffirmClient$1.onResponse(AffirmClient.java:86)
       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:71)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```
This seems similar to: https://github.com/square/retrofit/issues/3751 
I can't tell if you're using Retrofit, but considering your last release was in early 2022 I would guess you also need to make changes to support R8

**Comment by mateot1** [comment]
After looking more closely at `AffirmClient` I see you are not using Retrofit, but Okhttp directly. 
For now, keeping everything via `-keep class com.affirm.android.** { *; }` , seems to fix the crash. not sure if there are more precise rules you'd suggest.
