### ISSUE TITLE
Inconsistency between CheckoutRequest.java and Checkout.java

### ISSUE THREAD

**Issue by shrikanthkr** [Affirm/affirm-merchant-sdk-android#64]
Creation of Checkout class indicates that MetaData is a Nullable item, but while calling Affirm.startCheckout with this it crashes expecting MetaData to be NonNull. 

This started happening when we upgraded from  `2.0.6` to `2.0.10`

---

#### CrashLog

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.gson.JsonObject.addProperty(java.lang.String, java.lang.String)' on a null object reference
       at com.affirm.android.CheckoutRequest.create(CheckoutRequest.java:99)
       at com.affirm.android.CheckoutBaseActivity.onAttached(CheckoutBaseActivity.java:49)
       at com.affirm.android.AffirmActivity.onCreate(AffirmActivity.java:39)
       at android.app.Activity.performCreate(Activity.java:7815)
       at android.app.Activity.performCreate(Activity.java:7804)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

---

Device: Pixel 3
OS: 9
SDK Version: 2.0.10

**Comment by sichx** [comment]
@shrikanthkr 

Thank you for reporting this issue.  This is being addressed in this pr: https://github.com/Affirm/affirm-merchant-sdk-android/pull/62 

cc'ing @AmyBeall @kevinbartels
