### ISSUE TITLE
Error when currency is `CAD`: java.lang.NoSuchFieldException: CAD

### ISSUE THREAD

**Issue by SerhiiSolobaievUptech** [Affirm/affirm-merchant-sdk-android#67]
Fatal Exception: java.lang.AssertionError: java.lang.NoSuchFieldException: CAD
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:792)
       at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.Gson.getAdapter(Gson.java:556)
       at com.affirm.android.model.$AutoValue_Checkout$GsonTypeAdapter.<init>(.java:47)
       at com.affirm.android.model.Checkout.typeAdapter(Checkout.java:24)
       at com.affirm.android.model.AutoValueGson_AffirmAdapterFactory.create(AutoValueGson_AffirmAdapterFactory.java:39)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.Gson.toJson(Gson.java:696)
       at com.google.gson.Gson.toJson(Gson.java:683)
       at com.google.gson.Gson.toJson(Gson.java:638)
       at com.google.gson.Gson.toJson(Gson.java:618)
       at com.affirm.android.CheckoutRequest.parseToJsonObject(CheckoutRequest.java:187)
       at com.affirm.android.CheckoutRequest.create(CheckoutRequest.java:93)
       at com.affirm.android.CheckoutBaseActivity.onAttached(CheckoutBaseActivity.java:49)
       at com.affirm.android.AffirmActivity.onCreate(AffirmActivity.java:39)
       at android.app.Activity.performCreate(Activity.java:7955)
       at android.app.Activity.performCreate(Activity.java:7944)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by wangdaliu** [comment]
@SerhiiSolobaievUptech Thanks for your feedback. You can temporarily add the following content to `proguard-rules.pro` of the project, we will add it to the SDK in the next version. Thanks!
```
-keep class com.affirm.android.** { *; }
```

**Comment by SerhiiSolobaievUptech** [comment]
Hey, thanks for the reply!

Ok, I'll add it and let you know

**Comment by SerhiiSolobaievUptech** [comment]
Hey @wangdaliu 
Confirmed fix with adding models to `proguard-rules.pro` file
