### ISSUE TITLE
Affirm Fetch Promotion Crash 

### ISSUE THREAD

**Issue by shangeethsivan** [Affirm/affirm-merchant-sdk-android#71]
We have been recently seeing crashes while fetching affirm Promotion text. The scenario occurs when affirm outages happen. 
### Crashlog:
```
Fatal Exception: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
       at com.google.gson.Gson.fromJson(Gson.java:939)
       at com.google.gson.Gson.fromJson(Gson.java:865)
       at com.affirm.android.AffirmHttpClient.createExceptionAndTrackFromResponse(AffirmHttpClient.java:105)
       at com.affirm.android.PromoRequest$1.onResponse(PromoRequest.java:134)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```
> Affirm SDK Version 2.0.11
> Android OS: 9
It would  be great if there is way to throw the exception out by some manner so the client applications can handle it. At this point, client applications can't handle the exception as it doesn't occur in the layer where the PromotionRequest is triggered, wrapping a try catch is not helping.

**Comment by shangeethsivan** [comment]
@wangdaliu Can you please help with this !

**Comment by vcello** [comment]
@shangeethsivan can you let us know for which merchant(s) we're seeing this happen?

**Comment by shangeethsivan** [comment]
@vcello are you in need of the merchant name ?
